### ISSUE TITLE
Node12 is deprecated

### ISSUE THREAD

**Issue by WtfJoke** [mbogh/test-ssl-action#4]
Hey @mbogh 

Thank you for creating this action :)

The action currently still runs on node12. Node12 is eol and soon Node16.
Would be great if you can release a node16 version.

> The following actions uses node12 which is deprecated and will be forced to run on node16: mbogh/test-ssl-action@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

![grafik](https://github.com/mbogh/test-ssl-action/assets/7139697/d99b184c-26dc-4e04-9ba7-bbf227a31874)

EDIT: Will be fixed with https://github.com/mbogh/test-ssl-action/pull/3

**Comment by mbogh** [comment]
Hi @WtfJoke, thanks for the issue, think I will go for Node18, just to be a bit more future proof :)

Will fix it later today

**Comment by mbogh** [comment]
Closed by #6 and available in v3

**Comment by WtfJoke** [comment]
Thank you!

**Comment by spaze** [comment]
Thanks for the new release! 🥳

Btw, seems like it's still `node16`, not 18, hope it's intentional.

**Comment by WtfJoke** [comment]
Since node16 is now eol, just wanted to let you know, you can use node20 now :)

See https://github.com/actions/runner/issues/2619#issuecomment-1679003443

There seems to be however no official anouncement/docs update yet

**Comment by mbogh** [comment]
Thanks I will try to update to node20, it failed last time 👯

**Comment by mbogh** [comment]
It is now done, also updated v3 to point to v3.0.1

**Comment by WtfJoke** [comment]
Awesome, thank you

**Comment by SchoNie** [comment]
Hello @mbogh,

Thanks for creating this action!

The v3 and v3.0.1 still point to d48191d03757ce541ad9ab7ceda97923053710ac with node16.
While the update and main branch with node20 is [2 commits ahead](https://github.com/mbogh/test-ssl-action/compare/v3.0.1...main) of the tagged version.
So the tagged actions even 3.0.1 uses node16 and gives the warning.

I am currently using: `mbogh/test-ssl-action@6bad4e83e29bca36d5570a00736a0b9d63e52643` which works, but would be nice if you could tag the correct commit.

**Comment by mbogh** [comment]
> Hello @mbogh,
> 
> Thanks for creating this action!
> 
> The v3 and v3.0.1 still point to [d48191d](https://github.com/mbogh/test-ssl-action/commit/d48191d03757ce541ad9ab7ceda97923053710ac) with node16. While the update and main branch with node20 is [2 commits ahead](https://github.com/mbogh/test-ssl-action/compare/v3.0.1...main) of the tagged version. So the tagged actions even 3.0.1 uses node16 and gives the warning.
> 
> I am currently using: `mbogh/test-ssl-action@6bad4e83e29bca36d5570a00736a0b9d63e52643` which works, but would be nice if you could tag the correct commit.

Added a new v3.0.2 and update v3 to point to same hash
